import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import MyUrl from "./myurl";
import Particles from "./myurl/particles";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>MyMiniUrl</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MyUrl />
    </>
  );
}
